#!/usr/bin/env python3
"""Generates fast6502.rs: a compact fast path for the documented NMOS 6502 opcodes
that operates on mos6502's CPU struct and matches its behaviour exactly (cycle
counts, including its page-cross rules; flag results; the order of every bus access).

The interpreter body is hand-written in tools/fast6502_body.rs; this script fills
in the opcode table. It is table-driven rather than one match arm per opcode so
the hot loop fits the Playdate's 16 KB instruction cache.

Anything not covered (BRK, undocumented opcodes, ADC/SBC in decimal mode,
instructions fetched from zero page) returns None and runs through mos6502.

Usage: gen_fast6502.py OUT.rs
"""
import pathlib
import sys

MODES = ["imp", "acc", "imm", "zp", "zpx", "zpy", "abs", "absx", "absy", "izx", "izy", "ind", "rel"]
KINDS = ["SLOW", "ORA", "AND", "EOR", "ADC", "SBC", "CMP", "CPX", "CPY", "LDA", "LDX", "LDY", "BIT",
         "STA", "STX", "STY", "ASL", "LSR", "ROL", "ROR", "INC", "DEC", "BR", "JMP", "JSR", "RTS", "RTI",
         "PHA", "PHP", "PLA", "PLP", "CLF", "SEF", "TAX", "TAY", "TXA", "TYA", "TSX", "TXS",
         "INX", "INY", "DEX", "DEY", "NOP"]
FLAG = {"C": 0x01, "Z": 0x02, "I": 0x04, "D": 0x08, "V": 0x40, "N": 0x80}
BRANCHES = {"BPL": ("N", 0), "BMI": ("N", 1), "BVC": ("V", 0), "BVS": ("V", 1),
            "BCC": ("C", 0), "BCS": ("C", 1), "BNE": ("Z", 0), "BEQ": ("Z", 1)}
FLAG_OPS = {"CLC": ("CLF", "C"), "SEC": ("SEF", "C"), "CLI": ("CLF", "I"), "SEI": ("SEF", "I"),
            "CLV": ("CLF", "V"), "CLD": ("CLF", "D"), "SED": ("SEF", "D")}

# (opcode, mnemonic, mode, base cycles) for every documented opcode but BRK.
OPS = []


def group(mn, codes, modes, cycles):
    OPS.extend(zip(codes, [mn] * len(codes), modes, cycles))


for mn, base in [("ORA", 0x00), ("AND", 0x20), ("EOR", 0x40), ("ADC", 0x60), ("LDA", 0xA0), ("CMP", 0xC0), ("SBC", 0xE0)]:
    group(mn, [base + o for o in (0x09, 0x05, 0x15, 0x0D, 0x1D, 0x19, 0x01, 0x11)],
          ["imm", "zp", "zpx", "abs", "absx", "absy", "izx", "izy"], [2, 3, 4, 4, 4, 4, 6, 5])
group("STA", [0x85, 0x95, 0x8D, 0x9D, 0x99, 0x81, 0x91], ["zp", "zpx", "abs", "absx", "absy", "izx", "izy"], [3, 4, 4, 5, 5, 6, 6])
for mn, base in [("ASL", 0x00), ("ROL", 0x20), ("LSR", 0x40), ("ROR", 0x60)]:
    group(mn, [base + o for o in (0x0A, 0x06, 0x16, 0x0E, 0x1E)], ["acc", "zp", "zpx", "abs", "absx"], [2, 5, 6, 6, 7])
group("INC", [0xE6, 0xF6, 0xEE, 0xFE], ["zp", "zpx", "abs", "absx"], [5, 6, 6, 7])
group("DEC", [0xC6, 0xD6, 0xCE, 0xDE], ["zp", "zpx", "abs", "absx"], [5, 6, 6, 7])
group("LDX", [0xA2, 0xA6, 0xB6, 0xAE, 0xBE], ["imm", "zp", "zpy", "abs", "absy"], [2, 3, 4, 4, 4])
group("LDY", [0xA0, 0xA4, 0xB4, 0xAC, 0xBC], ["imm", "zp", "zpx", "abs", "absx"], [2, 3, 4, 4, 4])
group("STX", [0x86, 0x96, 0x8E], ["zp", "zpy", "abs"], [3, 4, 4])
group("STY", [0x84, 0x94, 0x8C], ["zp", "zpx", "abs"], [3, 4, 4])
group("CPX", [0xE0, 0xE4, 0xEC], ["imm", "zp", "abs"], [2, 3, 4])
group("CPY", [0xC0, 0xC4, 0xCC], ["imm", "zp", "abs"], [2, 3, 4])
group("BIT", [0x24, 0x2C], ["zp", "abs"], [3, 4])
for mn, c in [("BPL", 0x10), ("BMI", 0x30), ("BVC", 0x50), ("BVS", 0x70), ("BCC", 0x90), ("BCS", 0xB0), ("BNE", 0xD0), ("BEQ", 0xF0)]:
    OPS.append((c, mn, "rel", 2))
for mn, c, cy in [("CLC", 0x18, 2), ("SEC", 0x38, 2), ("CLI", 0x58, 2), ("SEI", 0x78, 2), ("CLV", 0xB8, 2),
                  ("CLD", 0xD8, 2), ("SED", 0xF8, 2), ("TAX", 0xAA, 2), ("TAY", 0xA8, 2), ("TXA", 0x8A, 2),
                  ("TYA", 0x98, 2), ("TSX", 0xBA, 2), ("TXS", 0x9A, 2), ("INX", 0xE8, 2), ("INY", 0xC8, 2),
                  ("DEX", 0xCA, 2), ("DEY", 0x88, 2), ("NOP", 0xEA, 2), ("PHA", 0x48, 3), ("PHP", 0x08, 3),
                  ("PLA", 0x68, 4), ("PLP", 0x28, 4), ("RTS", 0x60, 6), ("RTI", 0x40, 6)]:
    OPS.append((c, mn, "imp", cy))
OPS += [(0x4C, "JMP", "abs", 3), (0x6C, "JMP", "ind", 5), (0x20, "JSR", "abs", 6)]
assert len(OPS) == 150 and len({o[0] for o in OPS}) == 150


def entry(mn, mode, cycles):
    """Packs kind (bits 0-5), mode (6-9), cycles (10-13) and a parameter (16-24)."""
    kind, param = mn, 0
    if mn in BRANCHES:
        flag, taken_if_set = BRANCHES[mn]
        kind, param = "BR", FLAG[flag] | (0x100 if taken_if_set else 0)
    elif mn in FLAG_OPS:
        kind, flag = FLAG_OPS[mn]
        param = FLAG[flag]
    return KINDS.index(kind) | MODES.index(mode) << 6 | cycles << 10 | param << 16


table = [0] * 256  # 0 = SLOW
for code, mn, mode, cycles in OPS:
    table[code] = entry(mn, mode, cycles)

consts = "\n".join([f"const {k}: u32 = {i};" for i, k in enumerate(KINDS)] +
                   [f"const M_{m.upper()}: u32 = {i};" for i, m in enumerate(MODES)])
rows = "\n".join("    " + " ".join(f"0x{v:07X}," for v in table[i:i + 8]) for i in range(0, 256, 8))

body = (pathlib.Path(__file__).parent / "fast6502_body.rs").read_text()
out = ("// Generated by tools/gen_fast6502.py from tools/fast6502_body.rs. Do not edit.\n\n"
       + body.replace("// @CONSTS@", consts).replace("// @TABLE@", rows))
pathlib.Path(sys.argv[1]).write_text(out)
print(f"wrote {sys.argv[1]} ({len(OPS)} opcodes)")
