#!/usr/bin/env python3
"""Generates src/gb2312_table.h: Unicode -> index into the 16x16 GB2312 hanzi
font at the start of the dictionary's 8.BIN (rows 16-87, 94 glyphs per row)."""
import pathlib

pairs = []
for qu in range(16, 88):
    for wei in range(1, 95):
        try:
            ch = bytes([0xA0 + qu, 0xA0 + wei]).decode("gb2312")
        except UnicodeDecodeError:
            continue
        pairs.append((ord(ch), (qu - 16) * 94 + wei - 1))
pairs.sort()

out = pathlib.Path(__file__).resolve().parent.parent / "src" / "gb2312_table.h"
lines = [
    "// Generated by tools/gen_gb2312.py. Do not edit.",
    "// Sorted {Unicode code point, glyph index} pairs for GB2312 hanzi; glyph i is",
    "// the 32 bytes (16 rows of 16 bits, MSB first) at 8.BIN offset i * 32.",
    "#pragma once",
    "#include <stdint.h>",
    f"#define GB2312_GLYPHS {72 * 94}",
    f"static const uint16_t gb2312_table[{len(pairs)}][2] = {{",
]
for i in range(0, len(pairs), 6):
    lines.append("    " + " ".join(f"{{0x{u:04X},{g}}}," for u, g in pairs[i:i + 6]))
lines.append("};")
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out} ({len(pairs)} glyphs)")
